#: import environ os.environ
#: import gch kivy.utils.get_color_from_hex
#: import StiffScrollEffect kivymd.effects.stiffscroll.StiffScrollEffect
#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import gch kivy.utils.get_color_from_hex
#:import Animation kivy.animation.Animation
# <DetailsButton>:


<PropertyListItem>
    size_hint_y: None
    padding: dp(10)
    spacing: dp(20)
    height: dp(120)

    canvas:
        Color:
            rgba:
                self.theme_cls.divider_color
        Line:
            points: (root.x+dp(16), root.y, root.x+self.width-dp(16)-0, root.y)

    MDBoxLayout:
        adaptive_size: True
        pos_hint: {"center_x": .5, "center_y": .5}

        FitImage:
            source: root.prop_image
            size_hint: (None, None)
            size: (dp(110), dp(100))
            radius: [dp(7),]

        # MDLabel:
        #     text: root.prop_auction_type
        #     font_style: "Caption"
        #     pos_hint: {"center_x": .5, "center_y": .9}

    MDBoxLayout:
        orientation: "vertical"
        adaptive_height: True
        pos_hint: {"center_x": .5, "center_y": .5}
        spacing: dp(15)

        MDLabel:
            text: root.prop_title
            font_style: "Subtitle1"
            adaptive_height: True

        MDLabel:
            text: root.prop_location
            font_style: "Subtitle2"
            theme_text_color: "Hint"
            adaptive_height: True

        MDLabel:
            text: root.prop_price
            font_style: "Caption"
            theme_text_color: "Hint"
            adaptive_height: True

    MDBoxLayout:
        orientation: "vertical"
        padding: "10dp"
        adaptive_height: True
        spacing: dp(30)

        # adaptive_size: True
        # pos_hint: {"center_x": .6}
        MDFloatLayout:
            size_hint_x: None
            size_hint_y: None
            height: "18dp"
            width: "45dp"
            pos_hint: {"center_x": .94}
            adaptive_height: True

            canvas:
                Color:
                    rgba: 121/255, 134/255, 203/255, .6
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(3),]

            MDIconButton:
                icon: "eye"
                pos_hint : {"center_x": .2, "center_y": .5}
                user_font_size: "14sp"

            MDLabel:
                text: root.prop_views
                pos_hint: {"center_x": .9, "center_y": .5}
                font_style: "Caption"

        DetailButton:
            size_hint_x: None
            size_hint_y: None
            height: "40dp"
            width: "80dp"
            pos_hint: {"center_x": .85}
            adaptive_height: True
            canvas:
                Color:
                    rgba: 121/255, 134/255, 203/255, .6
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(3),]

            on_release:
                print("Clicked Details")

            MDLabel:
                text: "Details"
                pos_hint: {"center_x": .2, "center_y": .5}
                font_style: "Caption"

            MDIconButton:
                icon: "chevron-right"
                pos_hint : {"center_x": .9, "center_y": .5}
                user_font_size: "14sp"

<DMREToolbar>
    md_bg_color: gch("#7986cb")
    # adaptive_height: True
    size_hint_y: None
    height: "50dp"
    padding: "10dp"

    PreviousImage:
        id: button_menu
        source: "logo.png"
        size_hint_x: None
        width: root.height
        on_release:
            # print(root.nav_bar)
            root.scr_manager.transition.direction = "right"
            root.scr_manager.current = "Home" \
            if root.scr_manager.current in ["Listings", "Notifications", "Profile", "Settings", "Chat"] \
            else "Home"
            app.call_from_nav_item("set_home_active")

    MDLabel:
        id: title
        text: root.title
        bold: True
        color: root.theme_cls.text_color
        adaptive_width: True

    Widget:
        size_hint_x: None
        width: "10dp"

    MDTextField:
        id: search_field
        pos_hint: {"center_y": .5}
        disabled: True
        opacity: 0
        color_mode: "custom"
        font_size: "14sp"
        line_color_focus: root.theme_cls.opposite_bg_normal
        on_focus: if not self.focus: self.text = ""; root.set_search_field()

    MDIconButton:
        icon: "magnify"
        pos_hint: {"center_y": .5}
        on_release: root.set_search_field()

    MDIconButton:
        id: button_tune
        icon: "tune"
        pos_hint: {"center_y": .5}
        on_release:
            root.scr_manager.transition.direction = "right"
            root.scr_manager.current = "Settings"
            app.call_from_nav_item("set_all_inactive")

            # app.root.current = "rally register screen" ==== for logout

<NavigationItem>
    size_hint: None, None
    size: (dp(40), dp(40))
    pos_hint: {"center_x": .5, "center_y": .5}

    MDIcon:
        id: _icon
        icon: root.icon
        halign: "center"
        size_hint: (None, None)
        size: (root.height, root.height)
        theme_text_color: "Custom"
        text_color: root.icon_color

    FloatLayout:
        size_hint_x: None
        width: root.width - _icon.width

        MDLabel:
            id: _label
            text: root.text
            opacity: 0
            halign: "center"
            bold: True
            font_style: "Button"
            adaptive_size: True
            pos_hint: {"center_x": .5, "center_y": .5}

<NavigationBar>:
    size_hint: (None, None)
    height: dp(65)
    md_bg_color: gch("#7986cb")


    BoxLayout:
        id: _button_box

<RootScreen>
    # md_bg_color: gch("#fffefe")

    MDBoxLayout:
        id : root_screen_layout
        orientation: 'vertical'

        DMREToolbar:
            scr_manager : scr_manager
            id: toolbar_listing
            title: "Home"
            pos_hint: {"top": 1}
            path_to_icon_menu: "lopo.png"
            path_to_icon_logo: "logo.png"

        ScreenManager:
            id: scr_manager

            HomeScreen:
                id: home_screen
                name: "Home"

                MDLabel:
                    text: 'Home Screen'
                    halign: 'center'

            ChatScreen:
                id : chat_screen
                name: "Chat"

                MDLabel:
                    text: 'Chat Screen'
                    halign: 'center'

            ListingScreen:
                id: listing_screen
                name: "Listings"

                MDBoxLayout:
                    canvas.before:
                        Color:
                            rgba: gch("#fffefe")
                        RoundedRectangle:
                            size: self.size
                            pos: self.pos
                            radius: [dp(20), dp(20), 0, 0]

                    ScrollView:

                        MDList:
                            id : real_estate_items

                            MDBoxLayout:
                                adaptive_height: True
                                padding: [dp(10), dp(4), dp(25), dp(10)]

                                MDLabel:
                                    text: "Explore All Real Estate Properties"
                                    font_style: "Subtitle2"
                                    theme_text_color: "Hint"
                                    adaptive_height: True

            NotificationsScreen:
                id: notification_screen
                name: "Notifications"

                MDLabel:
                    text: 'Notification Screen'
                    halign: 'center'

            ProfileScreen:
                id: profile_screen
                name: "Profile"

                MDLabel:
                    text: 'Profile Screen'
                    halign: 'center'

            SettingScreen:
                id: setting_screen
                name: "Settings"

                MDLabel:
                    text: 'Settings Screen'
                    halign: 'center'

        NavigationBar:
            id: nav_bar

            NavigationItem:
                id : home_item
                text: "Home"
                icon: "home-variant-outline"
                title: "Home"
                on_release:
                    scr_manager.transition.direction = "right" \
                    if scr_manager.current in ["Listings", "Notifications", "Profile", "Chat"] \
                    else "left"
                    scr_manager.current = "Home"

            NavigationItem:
                id : chat_item
                text: "Chat"
                icon: "chat-outline"
                title: "Chats"
                on_release:
                    scr_manager.transition.direction = "right" \
                    if scr_manager.current in ["Listings", "Notifications", "Profile"] \
                    else "left"
                    scr_manager.current = "Chat"

            NavigationItem:
                id : listing_item
                text: "Listings"
                icon: "format-list-bulleted-square"
                title: "All Listings"
                on_release:
                    scr_manager.transition.direction = "right" \
                    if scr_manager.current in ["Notifications", "Profile"] \
                    else "left"
                    scr_manager.current = "Listings"

            NavigationItem:
                id : notifications_item
                text: "Notifications"
                icon: "bell-outline"
                title: "Notifications"
                on_release:
                    scr_manager.transition.direction = "left" \
                    if scr_manager.current in ["Home", "Chat", "Listings", "Settings"] \
                    else "right"
                    scr_manager.current = "Notifications"

            NavigationItem:
                id : profile_item
                text: "Profile"
                icon: "account-outline"
                title: "My Profile"
                on_release:
                    scr_manager.transition.direction = "left"\
                    if scr_manager.current in ["Chat", "Listings", "Notifications", "Home", "Settings"] \
                    else "right"
                    scr_manager.current = "Profile"

<ScrollView>
    bar_width: 0
    effect_cls: StiffScrollEffect

<RallyLabel@MDLabel>
    adaptive_height: True

<RallyListItem>
    size_hint_y: None
    height: dp(60)

    canvas:
        Color:
            rgba:
                self.theme_cls.divider_color
        Line:
            points: (root.x+dp(16), root.y, root.x+self.width-dp(16)-0, root.y)
    canvas.before:
        Color:
            rgba: gch("#31313b")
        Rectangle:
            size: self.size
            pos: self.pos

    MDBoxLayout:
        adaptive_size: True
        padding: dp(15)
        pos_hint: {"center_x": .5, "center_y": .5}

        MDIcon:
            icon: "minus-thick"
            halign: "center"
            pos_hint: {"center_y": .5}
            theme_text_color: "Custom"
            text_color: root.bar_color

            canvas.before:
                PushMatrix
                Rotate:
                    angle: 90
                    origin: self.center
            canvas.after:
                PopMatrix

    MDBoxLayout:
        orientation: 'vertical'
        adaptive_height: True
        pos_hint: {"center_x": .5, "center_y": .5}
        spacing: dp(2)

        RallyLabel:
            text: root.text
            font_style: "Subtitle1"

        RallyLabel:
            text: root.secondary_text
            theme_text_color: "Hint"
            font_style: "Button"

    MDBoxLayout:
        orientation: 'vertical'
        padding: (0, 0, 0, dp(10))
        adaptive_height: True

        RallyLabel:
            text: root.tertiary_text
            theme_text_color: "Secondary"
            pos_hint: {"center_x": .5, "center_y": .5}
            halign: "right"
            font_style: "H3"
            font_size: sp(20)

    MDBoxLayout:
        adaptive_size: True
        padding: dp(15)
        pos_hint: {"center_x": .5, "center_y": .5}

        MDIcon:
            icon: "chevron-right"
            halign: "center"
            pos_hint: {"center_y": .5}
            theme_text_color: "Hint"

<RegisterScreen>
    canvas:
        Color:
            rgba: gch("fffefe")
        Rectangle:
            pos: self.pos
            size: self.size

    MDBoxLayout:
        adaptive_height: True
        orientation: "vertical"
        spacing: dp(80)
        padding: dp(30)
        pos_hint: {"center_x": .5}

        Image:
            source: "logo.png"
            pos_hint: {"center_x": .5}
            size_hint: None, None

        MDBoxLayout:
            adaptive_height: True
            orientation: "vertical"
            spacing: dp(20)

            RallyTextField:
                hint_text: "Username"

            RallyTextField:
                hint_text: "Password"
                password: True
                password_mask: "•"

        MDBoxLayout:
            adaptive_height: True
            orientation: "vertical"
            spacing: dp(20)

            MDIconButton:
                icon: 'fingerprint'
                pos_hint: {"center_x": .5}
                user_font_size: dp(62)
                _no_ripple_effect: True
                on_release: root.parent.current = "rally root screen"

            MDTextButton:
                text: "Or Login with Touch ID"
                pos_hint: {"center_x": .5}

<RallyTextField@MDTextField>
    mode: 'fill'
    line_anim: False
    fill_color: (0, 0, 0, .4)

ScreenManager:
    id: screen_manager
    transition: FadeTransition()

    RootScreen:
        id : root_screen
        name: "rally root screen"

    RegisterScreen:
        id : register_screen
        name: "rally register screen"
